fix: add tests for auth endpoint (#5)
* fix: add tests for auth endpoint

* fix: update README.md, badge for coverage

* fix: parse coverage report

* fix: view tests coverage

* fix: find coverage

* fix: run tests and show coverage

* fix: output coverage in additional step

* fix: do not run tests twice

* fix: path to coverage

* fix: badge for coverage

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -96,3 +96,54 @@ jobs:
       - name: Run Mypy
         run: |
           make mypy
+
+  coverage:
+    name: Run Test Coverage
+    runs-on: ubuntu-latest
+    needs: setup
+    env:
+      VENV_PATH: ${{ github.workspace }}/venv/bin
+      POETRY_VIRTUALENVS_PATH: ${{ github.workspace }}/venv
+      SECRET_KEY: "CI_SECRET_KEY"
+    steps:
+      - uses: actions/checkout@v4
+
+      - name: Set up Python
+        uses: actions/setup-python@v5
+        with:
+          python-version: "3.13.2"
+
+      - name: Restore cached virtualenv
+        uses: actions/cache@v4
+        with:
+          path: venv
+          key: venv-${{ runner.os }}-${{ github.ref_name }}-${{ hashFiles('pyproject.toml') }}
+          restore-keys: |
+            venv-${{ runner.os }}-${{ github.ref_name }}-
+
+      - name: Run Test Coverage and Extract %
+        id: coverage
+        run: |
+          make coverage
+          COVERAGE_LINE=$(venv/bin/coverage report | grep TOTAL)
+          echo "Parsed output from coverage is $COVERAGE_LINE"
+          PERCENT=$(echo "$COVERAGE_LINE" | awk '{print $NF}' | tr -d '%')
+          echo "Coverage percentage: $PERCENT"
+          echo "coverage=$PERCENT" >> "$GITHUB_OUTPUT"
+
+      - name: View Coverage %
+        run: |
+          echo "Coverage percentage: ${{ steps.coverage.outputs.coverage }}"
+          if [ "${{ steps.coverage.outputs.coverage }}" -lt 80 ]; then
+            echo "Coverage is below 80%, failing the job."
+            exit 1
+          else
+            echo "Coverage is above 80%, passing the job."
+          fi
+
+      - name: Upload coverage to Codecov
+        uses: codecov/codecov-action@v4
+        with:
+          files: ./coverage.xml
+          token: ${{ secrets.CODECOV_TOKEN }}  # optional for public repos
+          
